core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=!"C:/Users/schup/miniconda3/Library/mingw64/libexec/git-core/git-credential-wincred.exe"
credential.helperselector.selected=wincred
user.email=schuppsimon5@gmail.com
user.name=LuposX
gui.recentrepo=C:/Users/schup/OneDrive/Documents/University
http.version=HTTP/1.1
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/MonkeManX/monkemanx.github.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
